name: Build and Deploy from fin_chart

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout chart_maker repository
        uses: actions/checkout@v3
        with:
          repository: Tradeable/chart_maker
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout fin_chart repository
        uses: actions/checkout@v3
        with:
          repository: adityagohad/fin_chart
          ref: dev # Use the dev branch
          path: fin_chart

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0" # Update to your Flutter version
          channel: "stable"

      - name: Get dependencies for fin_chart
        run: |
          cd fin_chart
          flutter pub get
          cd example
          flutter pub get

      - name: Build Flutter Web
        run: |
          cd fin_chart/example
          flutter build web --release

      - name: Modify base href and copy files
        run: |
          # Remove the base href line
          sed -i 's|<base href="/">||g' fin_chart/example/build/web/index.html

          # Copy all files from the build directory to the chart_maker root
          cp -r fin_chart/example/build/web/* ./

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update chart example from fin_chart dev branch" || echo "No changes to commit"
          git push

# GitHub Pages will automatically deploy from the updated main branch
# if you have GitHub Pages configured in the repository settings
